/*
 *  Copyright (C) 2026 KeePassXC Team <team@keepassxc.org>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 2 or (at your option)
 *  version 3 of the License.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "EntrySnapshot.h"

#include "core/Entry.h"
#include "core/EntryAttributes.h"
#include "core/EntryAttachments.h"
#include "core/CustomData.h"

EntrySnapshot EntrySnapshot::capture(Entry* entry)
{
    EntrySnapshot s;

    s.entryId = entry->uuid();

    // Standard text fields
    s.title = entry->title();
    s.username = entry->username();
    s.password = entry->password();
    s.url = entry->url();
    s.notes = entry->notes();

    // Custom attributes (all non-default keys)
    const QStringList customKeys = entry->attributes()->customKeys();
    for (const QString& key : customKeys) {
        s.customAttributes.insert(key, entry->attributes()->value(key));
    }

    // Attachment key names (not the binary payload)
    s.attachmentKeys = entry->attachments()->keys();

    // Entry-level CustomData (skip auto-generated keys to reduce noise)
    const QStringList dataKeys = entry->customData()->keys();
    for (const QString& key : dataKeys) {
        if (entry->customData()->isAutoGenerated(key)) {
            continue;
        }
        s.customData.insert(key, entry->customData()->value(key));
    }

    // Other properties
    s.iconNumber = entry->iconNumber();
    s.expires = entry->timeInfo().expires();
    s.expiryTime = entry->timeInfo().expiryTime();
    s.tags = entry->tagList();
    s.autoTypeEnabled = entry->autoTypeEnabled();
    s.defaultAutoTypeSequence = entry->defaultAutoTypeSequence();

    // Display timestamps
    s.creationTime = entry->timeInfo().creationTime();
    s.lastModificationTime = entry->timeInfo().lastModificationTime();

    return s;
}
